name: Checks

on:
  pull_request:
    branches:
      - main
      - dev

jobs:
  lint:
    name: Lint and format check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node_version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint
        run: pnpm lint

  api-is-deployable-stageing:
    name: API is deployable to stageing
    if: github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node_version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Stageing is deployable
        run: pnpm --filter api deploy:stageing:dry

  api-is-deployable-production:
    name: API is deployable to production
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node_version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Stageing is deployable
        run: pnpm --filter api deploy:production:dry

  frontend-is-deployable-stageing:
    name: Frontend is deployable to stageing
    if: github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node_version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter frontend build

      - name: Stageing is deployable
        run: pnpm --filter frontend deploy:stageing:dry

  frontend-is-deployable-production:
    name: Frontend is deployable to production
    if: github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node_version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter frontend build

      - name: Stageing is deployable
        run: pnpm --filter frontend deploy:production:dry
  test-e2e:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: false

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright Browsers
        run: pnpm --filter frontend exec playwright install --with-deps

      - name: Run Playwright tests
        run: pnpm --filter frontend exec playwright test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  api-tests:
    name: API tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node_version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run API tests
        run: pnpm --filter api test
        env:
          DB_URL: ${{ secrets.DB_URL }}
      
