name: Deploy frontend to stageing

on:
    push:
        paths:
            - ./apps/frontend/**/*
        branches:
            - dev

jobs:
    deploy:
        runs-on: ubuntu/latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup pnpm
              uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

            - name: Setup Node
              uses: actions/setup-node@v5
              with:
                  node_version: 24
                  cache: pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Deploy
              run: pnpm --filter frontend deploy:stageing
