name: Deploy frontend to stageing

on:
  push:
    #paths:
    #  - apps/frontend/**
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      VITE_API_URL: https://precious-api-stageing.sid-doro-hd.workers.dev/

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node_version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm --filter frontend build

      - name: Deploy
        run: pnpm --filter frontend deploy:stageing
